### ISSUE TITLE
I think there is an error in https://github.com/ruby/curses/blob/master/sample/form.rb

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/curses#79]
I just tested this example:

    https://github.com/ruby/curses/blob/master/sample/form.rb

However had it crashed for me:

001_form.rb:46:in `driver': Unknown command (Curses::UnknownCommandError)
        from 001_form.rb:46:in `<main>'

The line was:

    else
       form.driver(ch)

I added some debug statement. I could cause this error by hitting the "Ende" (End)
key.

The key value for this was:

360

Is this the regular behaviour of curses to crash like that?

To me it is a bit strange that form.driver(ch) would not work.

I did not test it with other keys but I assume that some other keys also cause
this issue.

Edit: Actually I tested it with page down too. That also led to the same problem,
hopefully it can be reproduced by someone else.

**Comment by shugo** [comment]
It's the expected behavior of Form#driver because the underlying form_driver() causes an error when the given code is unknown.
I've fixed sample/form.rb to ignore Curses::UnknownCommandError.
